### ISSUE TITLE
How do I use this for my dataset?

### ISSUE THREAD

**Issue by shambhaviparashar** [guotong1988/NL2SQL-RULE#14]

**Comment by guotong1988** [comment]
prepare the data to the same format of Wikisql

**Comment by shambhaviparashar** [comment]
Can you please elaborate? Which specific files require changes? 
Is it possible to fetch multiple columns unlike sqlova?

**Comment by guotong1988** [comment]
The json format is elaborated in the README.

You should modify the model to select multiple columns.
