### ISSUE TITLE
两个额外特征

### ISSUE THREAD

**Issue by yuqinyuqinyuqin** [guotong1988/NL2SQL-RULE#17]
您在论文里面提到引入两个额外的特征：问句和表格中的cell的match向量，问句和列的match向量，为了更好的理解，我尝试去您的代码中找这块的代码，但不太能找得到，能麻烦大神能跟我说下 这块代码在哪个脚本里嘛？

**Comment by guotong1988** [comment]
https://github.com/guotong1988/NL2SQL-RULE/blob/master/data_and_model/output_entity.py
