### ISSUE TITLE
Problem while running train.py

### ISSUE THREAD

**Issue by Sourish97** [guotong1988/NL2SQL-RULE#2]
Hello, I tried to clone your repo and run it on my local system. However when I try a normal python train.py or the command mentioned in sqlova repository, I get the following error

`python train.py`
```
BERT-type: uncased_L-12_H-768_A-12
Batch_size = 32
BERT parameters:
learning rate: 1e-05
Fine-tune BERT: False
Traceback (most recent call last):
  File "train.py", line 703, in <module>
    model, model_bert, tokenizer, bert_config = get_models(args, BERT_PT_PATH)
  File "train.py", line 164, in get_models
    args.no_pretraining)
  File "train.py", line 124, in get_bert
    bert_config.print_status()
AttributeError: 'BertConfig' object has no attribute 'print_status'
```
When I comment out bert_config.print_status(), I get another error as following
```
BERT-type: uncased_L-12_H-768_A-12
Batch_size = 32
BERT parameters:
learning rate: 1e-05
Fine-tune BERT: False
Traceback (most recent call last):
  File "train.py", line 703, in <module>
    model, model_bert, tokenizer, bert_config = get_models(args, BERT_PT_PATH)
  File "train.py", line 164, in get_models
    args.no_pretraining)
  File "train.py", line 126, in get_bert
    model_bert = BertModel(bert_config)
TypeError: __init__() missing 2 required positional arguments: 'is_training' and 'input_ids'
```
Any solution to this?

**Comment by guotong1988** [comment]
I will upload the file.

**Comment by guotong1988** [comment]
Try `python3 train.py --seed 1 --bS 16 --accumulate_gradients 2 --bert_type_abb uS --do_train --lr 0.001 --lr_bert 0.00001 --max_seq_leng 222`

**Comment by guotong1988** [comment]
I have uploaded some code. Please update and try again.

**Comment by Sourish97** [comment]
Same error again with the python command you provided

**Comment by guotong1988** [comment]
I have uploaded the config file.

**Comment by guotong1988** [comment]
You should find why `bert_config.print_status()` fails.

**Comment by TobiasBrx** [comment]
I have the same error

**Comment by musamaalvi** [comment]
> I have the same error

Did you find the solution ?

**Comment by siddharthrawal121** [comment]
@Sourish97  @TobiasBrx @musamaalvi  Did u guys find anything?

**Comment by guotong1988** [comment]
I will take a look

**Comment by musamaalvi** [comment]
@siddharthrawal121 yes,

what I did is simply I stopped importing BertConfig. Comment the below line in your code

from bert.modeling import BertConfig, BertModel


After this copy all the code from bert.modeling file and paste it into train.py. This resolved the issue for me.

**Comment by siddharthrawal121** [comment]
Hi @musamaalvi. I tried it didnt work and when I checked the code there is no method or class in bert.config for print_status. Maybe they removed **print_status** in later version. Which bert version are you using?

**Comment by siddharthrawal121** [comment]
@musamaalvi Nvm , fixed the issue by using the the modelling.py in bert folder of **NL2SQL-RULE**

**Comment by guotong1988** [comment]
it seems `export PYTHONPATH=/your/project/root/` 
I guess.

**Comment by siddharthrawal121** [comment]
yes @guotong1988. I solved it
