### ISSUE TITLE
bertindex_knowledge and header_knowledge

### ISSUE THREAD

**Issue by cold-eye** [guotong1988/NL2SQL-RULE#20]
i'm struggling how to annotate bertindex_knowledge and header_knowledge, can you explain them? thanks

**Comment by guotong1988** [comment]
https://github.com/guotong1988/NL2SQL-RULE/blob/master/data_and_model/output_entity.py

**Comment by cold-eye** [comment]
yeah, i've seen the scripts output_entity.py,   but what's meaning of label [0,1,2,3,4]? If my datasets is different with yours, the scripts output_entity.py need to modify?
'bertindex_knowledge': [0, 3, 0, 0, 4, 0, 3, 0],
'header_knowledge': [0, 2, 0, 0, 0, 2]

**Comment by guotong1988** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/4702353/158959898-27658b78-16cb-4876-919b-718ae1f08b60.png">
<img width="481" alt="image" src="https://user-images.githubusercontent.com/4702353/158959942-3a5807c9-8e5d-41cc-83a8-28a252042fba.png">


<img width="483" alt="image" src="https://user-images.githubusercontent.com/4702353/158960190-09ae6078-564a-4a8d-b906-c1788ed0da99.png">
