### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by StanlyBabu** [guotong1988/NL2SQL-RULE#21]
If a have a SQL table how can I convert it to test_data and test_table to find answers to a question related to the test database table. Can you please help me with this issue.

**Comment by guotong1988** [comment]
Tips: you should process the data Format to the Same exact format.

**Comment by StanlyBabu** [comment]
Can you please help me with the code to process such tabular data.

**Comment by guotong1988** [comment]
Ref to: https://github.com/guotong1988/NL2SQL-RULE/blob/master/data_and_model/output_entity.py
