### ISSUE TITLE
missing training data

### ISSUE THREAD

**Issue by beyhangl** [guotong1988/NL2SQL-RULE#3]
Hey,

Could verify the dataset

>  './data_and_model/train_tok.jsonl' 
 

> './data_and_model/train_knowledge.jsonl' 

These are same ? Because your code reading train_tok but it's missing

**Comment by guotong1988** [comment]
No.
`train_knowledge.jsonl'` is generated from`train_tok.jsonl`.
You can get `train_tok.jsonl` from
https://drive.google.com/file/d/1iJvsf38f16el58H4NPINQ7uzal5-V4v4

**Comment by beyhangl** [comment]
thanks for quick response. 
I just wondering about how can we test it with our own data dictionary and example sentence?

**Comment by guotong1988** [comment]
https://github.com/guotong1988/NL2SQL-BERT/blob/master/data_and_model/output_entity.py

You can only cache the more important data.

**Comment by fromfuture-ai** [comment]
Has anyone managed to run this code, can please help?

I have cloned the code, downloaded the file from gDrive, put it in the folder, downloaded Bert another folder.... and then run the python3 train.py ..... command. It ran, for a few seconds. And does not create any output.

Can the author please have a look at the readme, giving a fresh look. I failed to follow. I have downloaded missing datasets, etc. and still not working. Sorry, a bit frustrating.
