### ISSUE TITLE
Key differences between NL2SQL-BERT and SQLova?

### ISSUE THREAD

**Issue by Bill-ai** [guotong1988/NL2SQL-RULE#6]
1. What is the main difference between **this** and **SQLova** models?
2. Can this model perform tasks on Multiple Tables or **join** operations?
3. How do I infer after converting my data to similar to train data?
4. **SOTA** for this _Text to SQL task._

**Comment by guotong1988** [comment]
1, this project use db content info,  SQLova not.
2, no.
3, see https://github.com/guotong1988/NL2SQL-BERT/blob/master/data_and_model/output_entity.py
4, this project is the SOTA for WikiSQL dataset.

**Comment by Bill-ai** [comment]
1. Can you just please be more elaborate on what "**db content info**" is?
2. What alternatives did you find to solve the multiple tables problem?

**Comment by guotong1988** [comment]
1, You can read the paper.
2, https://yale-lily.github.io/spider
