### ISSUE TITLE
Testing models with simple prediction - Generate predictions JSON files 

### ISSUE THREAD

**Issue by mellahysf** [guotong1988/NL2SQL-RULE#9]
I have 2 questions very close : 

1)How can i test the model using simple user question and schema table ? simply, how to do simple prediction ? 

2)How to generate predictions JSON files  (for WikiSQL TrainigSet and DevSet ?)

Thank you very much for helping me.

**Comment by guotong1988** [comment]
These features are not ready now but may be ready in the future.

**Comment by mellahysf** [comment]
Thank your for your response.

I want to generate CSV file that contains 4 columns  : Question-Schema-Logical Form Evaluation (true or false)-Execution Evaluation (true or false) for TrainingSet and DevSet of WikiSQL !! 
How can i do this ? possible from train.py directly ? 

Thank you again for helpping me.

**Comment by guotong1988** [comment]
Sorry, out of my knowledge.
